-- 한 줄 주석
/* 범위 주석 */ 

-- SQL 한 줄 실행 : CTRL + Enter

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER KH_JSH IDENTIFIED BY KH1234;

-- 접속 권한, 사용권한을 줌
GRANT RESOURCE, CONNECT TO KH_JSH;

-- 공간 할당
ALTER USER KH_JSH DEFAULT TABLESPACE 
USERS QUOTA 20M ON USERS;