-- *MEMBERS, BOARDS 테이블 생성
/*1) MEMBER_ID 컬럼에 PRIMARY KEY 제약조건 설정.

2) MEMBER_PWD 컬럼에 NOT NULL 제약조건 설정.

3) MEMBER_NAME 컬럼에 가변 길이 문자열 30byte 설정.*/


-- MEMBERS 테이블 생성

CREATE TABLE MEMBERS (

	MEMBER_ID VARCHAR2(20) ,	
	MEMBER_PWD VARCHAR2(20) NOT NULL,	
	MEMBER_NAME VARCHAR2(30),	
	MEMBER_AGE NUMBER,	
	MEMBER_EMAIL VARCHAR2(50),


	CONSTRAINT MEMBERS PRIMARY KEY (MEMBER_ID)

);

-- BOARDS 테이블 생성
/*
 * 
1) BOARD_NO 컬럼에 PRIMARY KEY 제약조건 설정.

2) BOARD_WRITER 컬럼에 MEMERS 테이블의 MEMBER_ID를 참조하는 FOREIGN KEY 제약조건 설정.

3) BOARD_REG_DATE(작성일) 컬럼에 현재 시간으로 기본값 설정
 * */

CREATE TABLE BOARDS(
	BOARD_NO NUMBER PRIMARY KEY,
	BOARD_TITLE VARCHAR2(100),
	BOARD_CONTENT VARCHAR2(4000),
	BOARD_WRITER VARCHAR2(20),
	BOARD_REG_DATE DATE DEFAULT CURRENT_DATE,
	
		CONSTRAINT BOARDS_FK FOREIGN KEY (BOARD_WRITER) REFERENCES MEMBERS (MEMBER_ID)
);




/*
 * 1) MEMBER_ID 에 PRIMARY KEY 제약 조건 설정에 구문이 잘못 작성되었습니다.
CONSTRAINT 구문이 빠져 있는 상태입니다.
그리고 테이블명을 작성해야 합니다.

2) MEMBER_NAME에 가변형으로 작성해야 하는데 고정형 CHAR로 작성되어 있습니다.
해당 부분을 수정해야 합니다. 

3) BOARD_WRITER FOREIGN KEY 설정에서 참조할 테이블에 대한 명령어가 잘못 작성되어 있습니다.
CONSTRAIN (참조하는 테이블) REFERENCES 등을 추가해야 합니다.

4) BOARD_REG_DATE 에서 현재 시간 기본값 설정 구문이 잘못 작성 되어 있습니다
'2023-03-22'을 수정해야 합니다. 


1 문제 해결
CONSTRAINT 구문과 테이블명임 MEMBER 추가 :
CONSTRAINT MEMBERS PRIMARY KEY (MEMBER_ID)

2 문제 해결
CHAR 를 VARCAR2 로 수정 :
MEMBER_NAME VARCHAR2(30)

3 문제 해결
CONSTRAINT 구문을 넣고 (자식테이블) 
FOREIGN KEY (자식테이블 참조 컬럼) 
REFERENCES (부모테이블) (부모테이블 참조컬럼) 작성 :
CONSTRAINT BOARDS_FK
FOREIGN KEY (BOARD_WRITER) 
REFERENCES MEMBERS (MEMBER_ID)

4 문제 해결
'2023-03-22' 구문을 CURRENT_DATE 로 수정 :
BOARD_REG_DATE DATE DEFAULT CURRENT_DATE



CONSTRAINT USER_NO_PK(테이블명) PRIMARY KEY (USER_NO)

CONSTRAINT GRADE_CODE_FK1 FOREIGN KEY (GRADE_CODE)
    REFERENCES USER_GRADE (GRADE_CODE)

CONSTRAINT GRADE_CODE_FK3
  FOREIGN KEY(GRADE_CODE)
  REFERENCES USER_GRADE3 (GRADE_CODE) 

FOREIGN KEY(컬럼명) REFERENCES 참조 테이블명(참조컬럼명)

- EMPLOYEE테이블의 DEPT_CODE에 외래키 제약조건 추가
-- 참조 테이블은 DEPARTMENT, 참조 컬럼은 DEPARTMENT의 기본키
ALTER TABLE EMPLOYEE
ADD CONSTRAINT DEPT_CODE_FK
FOREIGN KEY (DEPT_CODE)
REFERENCES DEPARTMENT; 
 * 
 * */