-- JMT 프로젝트 테스트용

-- 241022
SELECT * FROM NOTICE;
SELECT * FROM FAQ;


CREATE SEQUENCE SEQ_NOTICE_NO NOCACHE;

		INSERT INTO "NOTICE"
		VALUES(
			SEQ_NOTICE_NO.NEXTVAL,
			SEQ_NOTICE_NO.CURRVAL || '번째 공지 제목',
			SEQ_NOTICE_NO.CURRVAL || '번째 공지 게시글 내용입니다',
			DEFAULT, 'N',
			1, '이벤트');
			
		--ALTER table "NOTICE" ADD "NOTICE_CATEGORY" varchar2(50) DEFAULT '공지' NOT NULL;
		
		COMMIT;
		
	BEGIN
	FOR I IN 1..20 LOOP
		INSERT INTO "BOARD"
		VALUES(
			SEQ_NOTICE_NO.NEXTVAL,
			SEQ_NOTICE_NO.CURRVAL || '번째 공지글',
			SEQ_NOTICE_NO.CURRVAL || '번째 공지 게시글 내용입니다',
			DEFAULT, DEFAULT, 1, DEFAULT,
			CEIL(DBMS_RANDOM.VALUE(0,3))
		);
	END LOOP;
END;

-- 10/24 가장 첫 번째로 오게 될 글 확인 
SELECT *
FROM "NOTICE"
WHERE NOTICE_NO = (SELECT MAX(NOTICE_NO) FROM "NOTICE");

-- 10/24 FAQ 임시 게시글 넣기
SELECT * FROM FAQ;
		INSERT INTO "FAQ"
		VALUES(
			SEQ_FAQ_NO.NEXTVAL,
			SEQ_FAQ_NO.CURRVAL || '번째 FAQ 제목',
			SEQ_FAQ_NO.CURRVAL || '번째 FAQ 내용입니다',
			'N');
			
		
-- 11/01 음식 카테고리 추가
			INSERT INTO "CATEGORY"
		VALUES(
			SEQ_NOTICE_NO.NEXTVAL,
			'베트남');