-- JMT 프로젝트 테스트용

-- 241022
SELECT * FROM NOTICE;


CREATE SEQUENCE SEQ_NOTICE_NO NOCACHE;

		INSERT INTO "NOTICE"
		VALUES(
			SEQ_NOTICE_NO.NEXTVAL,
			SEQ_NOTICE_NO.CURRVAL || '번째 공지 제목',
			SEQ_NOTICE_NO.CURRVAL || '번째 공지 게시글 내용입니다',
			DEFAULT, 'N',
			1, '이벤트');
			
		--ALTER table "NOTICE" ADD "NOTICE_CATEGORY" varchar2(50) DEFAULT '공지' NOT NULL;
		
		COMMIT;
		
	BEGIN
	FOR I IN 1..20 LOOP
		INSERT INTO "BOARD"
		VALUES(
			SEQ_NOTICE_NO.NEXTVAL,
			SEQ_NOTICE_NO.CURRVAL || '번째 공지글',
			SEQ_NOTICE_NO.CURRVAL || '번째 공지 게시글 내용입니다',
			DEFAULT, DEFAULT, 1, DEFAULT,
			CEIL(DBMS_RANDOM.VALUE(0,3))
		);
	END LOOP;
END;