CREATE TABLE CUSTOMER(
	CUSTOMER_NO NUMBER PRIMARY KEY,
	CUSTOMER_NAME VARCHAR2(60) NOT NULL,
	CUSTOMER_TEL VARCHAR2(30) NOT NULL,
	CUSTOMER_ADDRESS VARCHAR2(200) NOT NULL
);

SELECT *
FROM CUSTOMER;

INSERT INTO CUSTOMER
VALUES(
	SEQ_CUSTOMER_NO.NEXTVAL, 
	'고길동', 
	'0410',
	 '도도도도도도');
	 
	COMMIT;